import { Input } from '@yobta/ui'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container max-w-lg mx-auto px-4">
        <h1 className="text-2xl my-4">Welcome Yobta</h1>

        <Input caption="Test yobta" />
        <button className="ui-button">Yarr</button>
      </main>

      <footer>footer</footer>
    </>
  )
}

export default Home
